services:
  gw2-storytracker:
    build: .
    container_name: gw2-storytracker
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.gw2-st.rule=Host(`gw2storytracker.com`) || Host(`www.gw2storytracker.com`)"
      - "traefik.http.routers.gw2-st.entrypoints=websecure"
      - "traefik.http.services.gw2-st.loadbalancer.server.port=8080"
    networks:
      - proxy

networks:
  proxy:
    external: true
